<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EndurQuizQuestion;

class EndurQuizSeeder extends Seeder
{
    public function run(): void
    {
        EndurQuizQuestion::truncate();

        $questions = [

            // ── Module 1: Introduction ─────────────────────────────────────────
            ['module_id' => 'introduction', 'sort_order' => 1,
             'question'  => 'What are the three core business areas in Endur?',
             'option_a'  => 'Trading, Operations, and Accounting',
             'option_b'  => 'Front Office, Middle Office, and Back Office',
             'option_c'  => 'Admin, Reference, and Market Manager',
             'option_d'  => 'Credit, Risk, and Settlement',
             'correct_option' => 'b'],

            ['module_id' => 'introduction', 'sort_order' => 2,
             'question'  => 'What sits at the centre of the Front Office, Middle Office, and Back Office in Endur?',
             'option_a'  => 'Portfolios',
             'option_b'  => 'Risk reports',
             'option_c'  => 'Transactions',
             'option_d'  => 'User accounts',
             'correct_option' => 'c'],

            ['module_id' => 'introduction', 'sort_order' => 3,
             'question'  => 'What does the Reference Manager manage?',
             'option_a'  => 'Market prices and volatility curves',
             'option_b'  => 'Trade capture and deal validation',
             'option_c'  => 'Parties, Portfolios, and Personnel',
             'option_d'  => 'Security groups and compliance audits',
             'correct_option' => 'c'],

            ['module_id' => 'introduction', 'sort_order' => 4,
             'question'  => 'Which office generates price fixings, trade confirmations, and account postings?',
             'option_a'  => 'Front Office',
             'option_b'  => 'Middle Office',
             'option_c'  => 'Back Office',
             'option_d'  => 'Risk Office',
             'correct_option' => 'c'],

            ['module_id' => 'introduction', 'sort_order' => 5,
             'question'  => 'What is OpenLink Central?',
             'option_a'  => 'A database server for trade storage',
             'option_b'  => 'A single entry point giving one-click access to all Endur managers',
             'option_c'  => 'A trading exchange integration layer',
             'option_d'  => 'A compliance reporting module',
             'correct_option' => 'b'],

            ['module_id' => 'introduction', 'sort_order' => 6,
             'question'  => 'Which manager defines the curve and index structure for commodity prices and volatilities?',
             'option_a'  => 'Admin Manager',
             'option_b'  => 'Trading Manager',
             'option_c'  => 'Market Manager',
             'option_d'  => 'Operations Manager',
             'correct_option' => 'c'],

            ['module_id' => 'introduction', 'sort_order' => 7,
             'question'  => 'What does the Credit Manager check?',
             'option_a'  => 'Portfolio mark-to-market valuations',
             'option_b'  => 'External counterparty exposures against credit limits',
             'option_c'  => 'Internal portfolio market risk lines',
             'option_d'  => 'Trade confirmation documents',
             'correct_option' => 'b'],

            ['module_id' => 'introduction', 'sort_order' => 8,
             'question'  => 'What three questions does the Accounting Manager answer when generating postings?',
             'option_a'  => 'Who, what, and why',
             'option_b'  => 'Buy, sell, or hold',
             'option_c'  => 'When to post, what to post, and where to post it',
             'option_d'  => 'Validate, settle, or close',
             'correct_option' => 'c'],

            ['module_id' => 'introduction', 'sort_order' => 9,
             'question'  => 'Which manager handles trade settlements, confirmations, and instrument fixings?',
             'option_a'  => 'Trading Manager',
             'option_b'  => 'Credit Manager',
             'option_c'  => 'Market Manager',
             'option_d'  => 'Operations Manager',
             'correct_option' => 'd'],

            ['module_id' => 'introduction', 'sort_order' => 10,
             'question'  => 'In which office is Value at Risk (VaR) calculated?',
             'option_a'  => 'Front Office',
             'option_b'  => 'Back Office',
             'option_c'  => 'Middle Office',
             'option_d'  => 'Admin Office',
             'correct_option' => 'c'],

            // ── Module 2: Common Functionality ─────────────────────────────────
            ['module_id' => 'common-functionality', 'sort_order' => 1,
             'question'  => 'What appears in the Browser Window before a query has been run?',
             'option_a'  => 'All trades in the database',
             'option_b'  => 'Only the Main Group folder — no data',
             'option_c'  => 'A blank screen with no menu',
             'option_d'  => 'The most recent query results',
             'correct_option' => 'b'],

            ['module_id' => 'common-functionality', 'sort_order' => 2,
             'question'  => 'How do you open the Query Manager in Endur?',
             'option_a'  => 'Press F5 to refresh the screen',
             'option_b'  => 'Click the Query icon on the toolbar or go to File > Query',
             'option_c'  => 'Double-click any row in the Table Viewer',
             'option_d'  => 'Press Ctrl+Q in any module',
             'correct_option' => 'b'],

            ['module_id' => 'common-functionality', 'sort_order' => 3,
             'question'  => 'What does the shorthand "5d" mean when entering dates in Endur?',
             'option_a'  => '5 decimal places',
             'option_b'  => '5 deals in the batch',
             'option_c'  => '5 days from today',
             'option_d'  => '5 dollar price increment',
             'correct_option' => 'c'],

            ['module_id' => 'common-functionality', 'sort_order' => 4,
             'question'  => 'What does the amount shorthand "3k" resolve to in Endur?',
             'option_a'  => '3,000,000',
             'option_b'  => '3,000',
             'option_c'  => '30,000',
             'option_d'  => '300',
             'correct_option' => 'b'],

            ['module_id' => 'common-functionality', 'sort_order' => 5,
             'question'  => 'Which keyboard shortcut opens the search dialog inside the Table Viewer?',
             'option_a'  => 'F5',
             'option_b'  => 'F2',
             'option_c'  => 'Ctrl+F',
             'option_d'  => 'Ctrl+S',
             'correct_option' => 'b'],

            ['module_id' => 'common-functionality', 'sort_order' => 6,
             'question'  => 'What can you export from the Table Viewer?',
             'option_a'  => 'PDF formatted reports',
             'option_b'  => 'Database backup files',
             'option_c'  => 'Data to Microsoft Excel',
             'option_d'  => 'PowerPoint slide decks',
             'correct_option' => 'c'],

            ['module_id' => 'common-functionality', 'sort_order' => 7,
             'question'  => 'What do Query Defaults automatically pre-filter by?',
             'option_a'  => 'Date range only',
             'option_b'  => 'Currency and commodity type',
             'option_c'  => 'Transaction Type, Transaction Status, and Internal Portfolios',
             'option_d'  => 'User name and assigned role',
             'correct_option' => 'c'],

            ['module_id' => 'common-functionality', 'sort_order' => 8,
             'question'  => 'What does the "!=" conditional operator mean in the Query Manager?',
             'option_a'  => 'Greater than or equal to',
             'option_b'  => 'Not equal to',
             'option_c'  => 'Approximately equal to',
             'option_d'  => 'Empty or null value',
             'correct_option' => 'b'],

            ['module_id' => 'common-functionality', 'sort_order' => 9,
             'question'  => 'Which shorthand letter means "millions" in Endur amount conventions?',
             'option_a'  => 'M (uppercase)',
             'option_b'  => 'MM',
             'option_c'  => 'm (lowercase)',
             'option_d'  => 'mil',
             'correct_option' => 'c'],

            ['module_id' => 'common-functionality', 'sort_order' => 10,
             'question'  => 'The Table Viewer appears consistently throughout Endur. What is its main purpose?',
             'option_a'  => 'Only for viewing trade blotters',
             'option_b'  => 'Only for displaying market price curves',
             'option_c'  => 'Displaying lists of any data type in a standard configurable grid',
             'option_d'  => 'Editing XML system configuration files',
             'correct_option' => 'c'],

            // ── Module 3: System Setup ──────────────────────────────────────────
            ['module_id' => 'system-setup', 'sort_order' => 1,
             'question'  => 'What are the "three Ps" managed by the Reference Manager?',
             'option_a'  => 'Prices, Positions, and Portfolios',
             'option_b'  => 'Processes, Postings, and Payments',
             'option_c'  => 'Parties, Portfolios, and Personnel',
             'option_d'  => 'Products, Pipelines, and Permissions',
             'correct_option' => 'c'],

            ['module_id' => 'system-setup', 'sort_order' => 2,
             'question'  => 'What does the Admin Manager handle?',
             'option_a'  => 'Trade capture and deal pricing',
             'option_b'  => 'System configuration, static data, security, and data model extension',
             'option_c'  => 'Real-time market price feeds',
             'option_d'  => 'Counterparty credit limit monitoring',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 3,
             'question'  => 'What is a Party Group in Endur?',
             'option_a'  => 'A group of traders sharing a portfolio',
             'option_b'  => 'A corporate structure containing Legal Entities and Business Units',
             'option_c'  => 'A collection of linked portfolios',
             'option_d'  => 'A set of related price indices',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 4,
             'question'  => 'Before a party can be used to book trades, what three things must be set up against it?',
             'option_a'  => 'Address, phone number, and email',
             'option_b'  => 'Portfolio, personnel record, and product list',
             'option_c'  => 'Account, Settlement Instructions, and Party Agreement',
             'option_d'  => 'Index, curve definition, and scenario',
             'correct_option' => 'c'],

            ['module_id' => 'system-setup', 'sort_order' => 5,
             'question'  => 'Which section of the Admin Manager contains the Activity Audit and Security Groups?',
             'option_a'  => 'General Administration',
             'option_b'  => 'Data Model Extension',
             'option_c'  => 'Compliance',
             'option_d'  => 'Energy Administration',
             'correct_option' => 'c'],

            ['module_id' => 'system-setup', 'sort_order' => 6,
             'question'  => 'What are the three types of Personnel records in Endur?',
             'option_a'  => 'Admin, Trader, and Analyst',
             'option_b'  => 'External, Internal, and Licensed User',
             'option_c'  => 'Front Office, Middle Office, and Back Office',
             'option_d'  => 'Manager, Supervisor, and Operator',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 7,
             'question'  => 'When "Party Agreement Required" is set to Yes on a Legal Entity, what does this enforce?',
             'option_a'  => 'The party must be pre-approved by compliance',
             'option_b'  => 'A valid party agreement must exist before any deal can be booked against that entity',
             'option_c'  => 'A legal review is automatically triggered',
             'option_d'  => 'The party is restricted to read-only access',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 8,
             'question'  => 'What does the Transportation Network section in Energy Administration configure?',
             'option_a'  => 'IT network routing and firewall rules',
             'option_b'  => 'Pipelines, delivery locations, zones, and network structures for physical commodity scheduling',
             'option_c'  => 'Email server routing for trade confirmations',
             'option_d'  => 'User login and access permissions',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 9,
             'question'  => 'What is Data Model Extension in the Admin Manager used for?',
             'option_a'  => 'Extending real-time market data feeds',
             'option_b'  => 'Adding custom fields beyond the standard Endur data model',
             'option_c'  => 'Expanding counterparty credit limits',
             'option_d'  => 'Extending trade maturity dates',
             'correct_option' => 'b'],

            ['module_id' => 'system-setup', 'sort_order' => 10,
             'question'  => 'What is a Portfolio in Endur?',
             'option_a'  => 'A collection of party agreements',
             'option_b'  => 'A financial instrument type',
             'option_c'  => 'A trader\'s book structure that holds deals of specified instrument types',
             'option_d'  => 'A market data curve set',
             'correct_option' => 'c'],

            // ── Module 4: Market & Trading ──────────────────────────────────────
            ['module_id' => 'market-and-trading', 'sort_order' => 1,
             'question'  => 'What is an Official Index used for in Endur?',
             'option_a'  => 'Internal stress testing calculations only',
             'option_b'  => 'Validating deals and end-of-day revaluations — only Official Indexes are included in P&L',
             'option_c'  => 'Tracking broker commission rates',
             'option_d'  => 'Generating trade confirmation documents',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 2,
             'question'  => 'What are the two sides of every index in Endur?',
             'option_a'  => 'Buy side and sell side',
             'option_b'  => 'Physical side and financial side',
             'option_c'  => 'Definition side and Input side',
             'option_d'  => 'Primary index and secondary index',
             'correct_option' => 'c'],

            ['module_id' => 'market-and-trading', 'sort_order' => 3,
             'question'  => 'Every trade in Endur has three identification numbers. What are they?',
             'option_a'  => 'Deal Number, Batch Number, and Reference Number',
             'option_b'  => 'Instrument Number, Deal Number, and Transaction Number',
             'option_c'  => 'Primary ID, Secondary ID, and Audit ID',
             'option_d'  => 'Portfolio ID, Book ID, and Position ID',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 4,
             'question'  => 'What is the difference between Input Date and Trade Date?',
             'option_a'  => 'They are always the same date',
             'option_b'  => 'Input Date is the business date the deal was agreed; Trade Date is when it was entered in the system',
             'option_c'  => 'Input Date is system-generated (when the record was entered); Trade Date is the business date the deal was agreed',
             'option_d'  => 'Input Date applies to futures; Trade Date applies to swaps',
             'correct_option' => 'c'],

            ['module_id' => 'market-and-trading', 'sort_order' => 5,
             'question'  => 'What status does a transaction reach after back office validation?',
             'option_a'  => 'Open',
             'option_b'  => 'Active',
             'option_c'  => 'Validated',
             'option_d'  => 'Confirmed',
             'correct_option' => 'c'],

            ['module_id' => 'market-and-trading', 'sort_order' => 6,
             'question'  => 'What are Trade Events and when are they generated?',
             'option_a'  => 'System error logs generated on any status change',
             'option_b'  => 'Automatically generated when a deal reaches Validated status — representing a roadmap of future actions on the deal',
             'option_c'  => 'Manual audit entries created by back office staff',
             'option_d'  => 'Market data refresh events triggered by price changes',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 7,
             'question'  => 'In Power Trading, what does a Product define?',
             'option_a'  => 'The price per megawatt-hour for the deal',
             'option_b'  => 'The days and hours — including holidays — during which electricity will be delivered',
             'option_c'  => 'The counterparty credit limit for power transactions',
             'option_d'  => 'The clearing venue and margin requirements',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 8,
             'question'  => 'What happens to the Transaction Number when a Validated deal is amended?',
             'option_a'  => 'It stays the same as the Deal Number',
             'option_b'  => 'It increments while the Deal Number stays the same — allowing you to trace back to the original',
             'option_c'  => 'Both numbers are deleted and reassigned from scratch',
             'option_d'  => 'It resets to zero for the new version',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 9,
             'question'  => 'What is a Composite Index in Endur?',
             'option_a'  => 'An index sourced directly from an official exchange feed',
             'option_b'  => 'An index derived from other indexes using pricing formulas',
             'option_c'  => 'A historical price series for backtesting',
             'option_d'  => 'An index entered manually by the trader',
             'correct_option' => 'b'],

            ['module_id' => 'market-and-trading', 'sort_order' => 10,
             'question'  => 'What does the Trading Manager Browser Focus Box show?',
             'option_a'  => 'A free-text search box for finding trades',
             'option_b'  => 'A condensed graphical view of your current query results',
             'option_c'  => 'A trade entry form for the selected instrument',
             'option_d'  => 'A real-time risk calculator',
             'correct_option' => 'b'],

            // ── Module 5: Deal Entry ────────────────────────────────────────────
            ['module_id' => 'deal-entry', 'sort_order' => 1,
             'question'  => 'What is the Primary Input screen used for in deal entry?',
             'option_a'  => 'Running pricing simulations against live market data',
             'option_b'  => 'Entering internal details, counterparty details, and deal economics such as commodity, volume, and dates',
             'option_c'  => 'Viewing the historical trade blotter',
             'option_d'  => 'Configuring market index curves',
             'correct_option' => 'b'],

            ['module_id' => 'deal-entry', 'sort_order' => 2,
             'question'  => 'What does NPV stand for in the context of deal pricing?',
             'option_a'  => 'Net Portfolio Value',
             'option_b'  => 'Nominal Price Value',
             'option_c'  => 'Net Present Value',
             'option_d'  => 'New Position Valuation',
             'correct_option' => 'c'],

            ['module_id' => 'deal-entry', 'sort_order' => 3,
             'question'  => 'What triggers the automatic generation of Trade Events on a deal?',
             'option_a'  => 'Entering the deal into the system',
             'option_b'  => 'Amending a previously validated deal',
             'option_c'  => 'Validating the deal',
             'option_d'  => 'Settling the deal at maturity',
             'correct_option' => 'c'],

            ['module_id' => 'deal-entry', 'sort_order' => 4,
             'question'  => 'When is the counterparty credit limit check performed in the deal lifecycle?',
             'option_a'  => 'At the time of initial deal entry',
             'option_b'  => 'At deal validation',
             'option_c'  => 'At deal settlement',
             'option_d'  => 'Only during end-of-day processing',
             'correct_option' => 'b'],

            ['module_id' => 'deal-entry', 'sort_order' => 5,
             'question'  => 'What are Portfolio Revaluations?',
             'option_a'  => 'Manual price overrides applied by the back office',
             'option_b'  => 'Simulations that price, value, and generate accounting entries for all transactions in a portfolio',
             'option_c'  => 'Credit line adjustments triggered by market moves',
             'option_d'  => 'Counterparty risk reviews run by the compliance team',
             'correct_option' => 'b'],

            ['module_id' => 'deal-entry', 'sort_order' => 6,
             'question'  => 'What is the key difference between using a Toolset versus the Trader Desktop for deal entry?',
             'option_a'  => 'Toolsets are web-based; Trader Desktop is a desktop application',
             'option_b'  => 'Toolsets enter one deal at a time per instrument; Trader Desktop allows multiple deals simultaneously with configurable defaults',
             'option_c'  => 'They are identical — just different views of the same form',
             'option_d'  => 'Toolsets are for futures only; Trader Desktop is for OTC products',
             'correct_option' => 'b'],

            ['module_id' => 'deal-entry', 'sort_order' => 7,
             'question'  => 'What does EOD stand for in Portfolio Revaluations?',
             'option_a'  => 'End of Deal',
             'option_b'  => 'Error on Delivery',
             'option_c'  => 'End of Day',
             'option_d'  => 'Execution on Demand',
             'correct_option' => 'c'],

            ['module_id' => 'deal-entry', 'sort_order' => 8,
             'question'  => 'What does Straight-Through-Processing (STP) mean in Endur?',
             'option_a'  => 'Trades go directly to settlement without back office validation',
             'option_b'  => 'Seamless integrated processing from trade entry through to sub-ledger posting with no manual re-keying between steps',
             'option_c'  => 'Automatic deal generation from market triggers',
             'option_d'  => 'Real-time market data integration into pricing',
             'correct_option' => 'b'],

            ['module_id' => 'deal-entry', 'sort_order' => 9,
             'question'  => 'What results does a Portfolio Revaluation produce?',
             'option_a'  => 'Only mark-to-market values',
             'option_b'  => 'Credit exposures and counterparty risk only',
             'option_c'  => 'Volume schedules and nomination data',
             'option_d'  => 'Accrued Interest, Cash Settlements, MTM, and Realised PnL',
             'correct_option' => 'd'],

            ['module_id' => 'deal-entry', 'sort_order' => 10,
             'question'  => 'What is a simulation in Endur deal management?',
             'option_a'  => 'A confirmed and booked trade',
             'option_b'  => 'Running the deal against current market data without saving any changes — to preview the impact on NPV',
             'option_c'  => 'A historical backtest against archived prices',
             'option_d'  => 'A regulatory stress-testing report',
             'correct_option' => 'b'],

        ];

        foreach ($questions as $q) {
            EndurQuizQuestion::create($q);
        }
    }
}
