<x-app-layout>
    <x-slot name="title">Reports</x-slot>

    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            <a href="{{ route('risk.dashboard') }}" class="text-muted small text-decoration-none">Risk &amp; Analytics</a>
            <span class="text-muted small"> / </span>
            <span class="small fw-semibold">Reports</span>
        </div>
    </div>

    <div class="row g-3 align-items-start">
        {{-- Generate form --}}
        <div class="col-lg-4">
            <div class="card card-etrm">
                <div class="card-header fw-semibold">Generate Report</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('risk.reports.generate') }}">
                        @csrf
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Report Type <span class="text-danger">*</span></label>
                            <select name="report_type" class="form-select @error('report_type') is-invalid @enderror">
                                <option value="">— Select —</option>
                                @foreach($types as $key => $label)
                                <option value="{{ $key }}" {{ old('report_type') === $key ? 'selected' : '' }}>{{ $label }}</option>
                                @endforeach
                            </select>
                            @error('report_type')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="mb-3">
                            <label class="form-label fw-semibold">As-of Date <span class="text-danger">*</span></label>
                            <input type="date" name="reporting_date"
                                   class="form-control @error('reporting_date') is-invalid @enderror"
                                   value="{{ old('reporting_date', date('Y-m-d')) }}">
                            @error('reporting_date')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <button type="submit" class="btn btn-primary w-100"
                                style="background:var(--etrm-secondary);border-color:var(--etrm-secondary);">
                            Download CSV
                        </button>
                    </form>
                </div>
            </div>
        </div>

        {{-- Report history --}}
        <div class="col-lg-8">
            <div class="card card-etrm">
                <div class="card-header fw-semibold">Report Run History</div>
                <div class="card-body p-0">
                    <table class="table table-etrm table-hover mb-0" style="font-size:.875rem;">
                        <thead>
                            <tr>
                                <th>Report</th>
                                <th>As-of Date</th>
                                <th>Format</th>
                                <th>Generated By</th>
                                <th>Generated At</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($reports as $r)
                            <tr>
                                <td class="fw-semibold">{{ \App\Models\Report::typeLabel($r->report_type) }}</td>
                                <td>{{ $r->reporting_date->format('d-M-Y') }}</td>
                                <td><span class="badge bg-secondary">{{ strtoupper($r->file_format) }}</span></td>
                                <td>{{ $r->generatedBy?->name ?? '—' }}</td>
                                <td class="text-muted small">{{ $r->created_at->format('d-M-Y H:i') }}</td>
                            </tr>
                            @empty
                            <tr><td colspan="5" class="text-center text-muted py-4">No reports generated yet.</td></tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                @if($reports->hasPages())
                <div class="card-footer py-2">{{ $reports->links() }}</div>
                @endif
            </div>
        </div>
    </div>
</x-app-layout>
